title = "Gitleaks Config without sourcegraph-access-token"
description = "Exclude Sourcegraph access token rule from scans"

# Import all default rules
[extend]
path = "https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml"

# Disable the Sourcegraph access token rule
[[rules]]
id = "sourcegraph-access-token"
disabled = true