# .github/workflows/gitleaks-full-history.yml
name: Gitleaks – Full History Scan

on:
  workflow_dispatch: {}           # manual run
  push:
    branches: [ "**" ]            # optional: scan on every push (expensive)
  pull_request:                   # optional: scan on PRs too
    branches: [ "**" ]

permissions:
  contents: read
  security-events: write          # needed to upload SARIF

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # IMPORTANT: needed to scan all commits

      - name: Install Gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | bash
          ./gitleaks version

      - name: Run Gitleaks over entire repo history
        run: |
          # Scan full git history; fail the job if leaks are found.
          ./gitleaks detect \
            --source . \
            --report-format sarif \
            --report-path gitleaks.sarif \
            --redact \
            --exit-code 1

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif