name: gitleaks
on:
  push:
    branches: [main]
  pull_request:
  #schedule:
  #  - cron: "0 4 * * *" # run once a day at 4 AM

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ARGS: "--format sarif"
          # GITLEAKS_ARGS: "tasky -f sarif -r sarif.json"

      - name: List files in workspace
        run: ls -al

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif